"""feat user.role

Revision ID: 5eb2dd907833
Revises: c77a0122a44a
Create Date: 2025-04-13 13:42:12.034714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5eb2dd907833'
down_revision: Union[str, None] = 'c77a0122a44a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE userrole AS ENUM ('user', 'admin')")
    op.add_column('users', sa.Column('role', sa.Enum('user', 'admin', name='userrole'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.execute("DROP TYPE userrole")
    # ### end Alembic commands ###
