"""add user - contact relations

Revision ID: c77a0122a44a
Revises: d7eb38218d26
Create Date: 2025-04-05 20:46:19.993408

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c77a0122a44a"
down_revision: Union[str, None] = "d7eb38218d26"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("contacts", sa.Column("user_id", sa.Integer(), nullable=True))
    op.alter_column("contacts", "birthdate", existing_type=sa.DATE(), nullable=False)
    op.create_foreign_key(
        None, "contacts", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "contacts", type_="foreignkey")
    op.alter_column("contacts", "birthdate", existing_type=sa.DATE(), nullable=True)
    op.drop_column("contacts", "user_id")
    # ### end Alembic commands ###
